# Generated by Django 5.0 on 2024-04-13 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0001_initial"),
        ("breweries", "0002_alter_brewery_num_beers"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="brewery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beers",
                to="breweries.brewery",
            ),
        ),
    ]
