# Generated by Django 5.0 on 2024-04-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beers", "0002_beer_brewery"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="label",
            field=models.ImageField(blank=True, upload_to="labels/"),
        ),
    ]
