# Generated by Django 5.2 on 2026-03-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beers", "0004_alter_beer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="beer",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
