# Generated by Django 5.2 on 2026-03-17 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_review_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(blank=True, upload_to="reviews/"),
        ),
    ]
