# Generated by Django 5.0 on 2024-03-18 04:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brewery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("country", models.CharField(blank=True, max_length=32)),
                ("url", models.URLField(blank=True)),
                ("num_beers", models.IntegerField()),
                (
                    "avg_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
            ],
        ),
    ]
