# Generated by Django 5.0 on 2024-04-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("breweries", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brewery",
            name="num_beers",
            field=models.IntegerField(default=0),
        ),
    ]
