# Generated by Django 5.2 on 2026-03-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("breweries", "0002_alter_brewery_num_beers"),
    ]

    operations = [
        migrations.AddField(
            model_name="brewery",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
